Translation/fr fr
OWASP/API-Security pull request #45
Opened 2021-07-09 18:15 UTC by datakime

2021-07-10 11:51 UTC, llegaz requested changes
First proposal, I will make a second review tomorrow for the rest of the document

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API1:2019 - Broken Object Level Authorization | Les API ont tendance à exposer des points d'accès qui gèrent les identifiants des objets, créant une large surface d'attaque des contrôles de niveaux
```suggestion
| API1:2019 - Broken Object Level Authorization | Les API ont tendance à exposer des points d'accès (endpoints) qui gèrent les identifiants d'objets (OID), créant une large surface d'attaque des contrôles de niveaux d'accès. Des contrôles d'autorisation doivent être effectués pour toute fonction qui accède à une source de données à partir d'entrées fournies par un utilisateur. |
```

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API1:2019 - Broken Object Level Authorization | Les API ont tendance à exposer des points d'accès qui gèrent les identifiants des objets, créant une large surface d'attaque des contrôles de niveaux
Je ne suis pas sûr mais je pense qu'il est bien de précisé aussi le mot en anglais ici car dans mon expérience personnelle quand il m'est arrivé de travailler ou développer des endpoints d'API, nous parlions entre collègues de endpoints et non de points d'accès ou de points de terminaison.

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implémentés incorrectement, permettant à des attaquants de compromettre des tokens d'authentification ou d'ex
```suggestion
| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implantés incorrectement, permettant à des attaquants d'obtenir des jetons (tokens) d'authentification ou d'exploiter des failles issues de défauts d'implantation logiciel afin d'endosser temporairement ou de manière permanente l'identité d'autres utilisateurs. La compromission de la capacité du système à identifier le client / utilisateur compromet la sécurité de l'API dans son ensemble. |
```

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implémentés incorrectement, permettant à des attaquants de compromettre des tokens d'authentification ou d'ex
Je sais que le terme compromettre à une saveur très particulière en IT Sec mais je pense que dans ce contexte le verbe se rapproche plus du sens d'exposer / mettre à nue ou/et donc obtenir.

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implémentés incorrectement, permettant à des attaquants de compromettre des tokens d'authentification ou d'ex
```suggestion
| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implémentés incorrectement, permettant à des attaquants de compromettre des tokens d'authentification ou d'exploiter des failles d'implémentation afin d'endosser temporairement ou de manière permanente l'identité d'autres utilisateurs. L'incapacité, pour un système, à identifier le client / utilisateur de manière fiable compromet la sécurité de l'API dans son ensemble. |
```

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API3:2019 - Excessive Data Exposure | En effectuant des implémentations génériques rapides, les développeurs ont tendance à exposer tous les attributs des objets sans prendre en considération leur
```suggestion
| API3:2019 - Excessive Data Exposure | En effectuant des implémentations génériques rapides, les développeurs ont tendance à exposer tous les attributs des objets sans prendre en considération leur confidentialité individuelle, se reposant sur les clients d'API pour effectuer un filtrage des données avant présentation à l'utilisateur. |
```

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API4:2019 - Lack of Resources & Rate Limiting | Bien souvent, les API n'imposent pas de restrictions sur la taille ou le nombre de ressources qui peuvent être requises par le client / l'utilisateur
```suggestion
| API4:2019 - Lack of Resources & Rate Limiting | Bien souvent, les API n'imposent pas de restrictions sur le nombre de requêtes, leurs tailles et le type de ressources demandant à être accédées par le client / l'utilisateur. Ceci impacte non seulement la performance du serveur d'API, aboutissant à un Déni de Service (DoS), mais cela constitue aussi une porte ouverte pour des failles d'authentification par force brute. |
```

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API6:2019 - Mass Assignment | La connexion de données fournies par le client (ex : JSON) aux modèles de données sans filtrage approprié par une liste de validation conduit généralement à l'assignat
```suggestion
| API6:2019 - Mass Assignment | La connexion de données fournies par le client (ex : JSON) aux modèles de données sans filtrage approprié par une liste de validation conduit généralement à l'assignation massive. En devinant les attributs des objets, en explorant les autres points d'accès de l'API, en lisant la documentation ou en incluant des attributs supplémentaires dans la charge utile (payload) des requêtes, les attaquants parviennent à modifier les attributs d'objets qu'ils ne devraient pas pouvoir modifier. |
```

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API6:2019 - Mass Assignment | La connexion de données fournies par le client (ex : JSON) aux modèles de données sans filtrage approprié par une liste de validation conduit généralement à l'assignat
Pareil, jamais entendu parlé de charge utile dans aucuns de mes jobs ni même à l'école d'ingé. Bref, comme pour endpoint j'ajouterai pour désambiguïser.

La charge utile me fait plutôt penser à un ascenseur qu'à une API

Ayant déjà travaillé sur des traductions concernant des APIs dans le milieu pro, c'est déjà ce que j'avais fait à l'époque.. j'avais gardé les 2 mots pour que tous le monde comprennent de quoi il est question.

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API6:2019 - Mass Assignment | La connexion de données fournies par le client (ex : JSON) aux modèles de données sans filtrage approprié par une liste de validation conduit généralement à l'assignat
```suggestion
| API6:2019 - Mass Assignment | La connexion de données fournies par le client (ex : JSON) aux modèles de données sans filtrage approprié par une liste de validation conduit généralement à l'assignation massive. En devinant les attributs des objets, en explorant les autres points d'accès de l'API, en lisant la documentation ou en incluant des attributs supplémentaires dans la charge utile des requêtes, les attaquants parviennent à modifier des propriétés d'objets qu'ils ne sont pas supposés accéder. |
```

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API9:2019 - Improper Assets Management | Les API ont tendance à exposer plus de points d'accès que les applications web traditionnelles, rendant très importante la nécessité d'une documentation app
```suggestion
| API9:2019 - Improper Assets Management | Les API ont tendance à exposer plus de points d'accès que les applications web traditionnelles, rendant très importante la nécessité d'une documentation appropriée et actualisée. Un inventaire précis des hôtes et des versions d'API déployées joue également un rôle important pour prévenir les problèmes tels que les versions obsolètes d'API et les points d'accès prévus pour le débogage pouvant être laissés exposés sur des serveurs de production. |
```

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API10:2019 - Insufficient Logging & Monitoring | L'insuffisance de logging et de monitoring, couplée à une intégration insuffisante ou absente à la réponse aux incidents, permet aux attaquants de p
```suggestion
| API10:2019 - Insufficient Logging & Monitoring | L'insuffisance d'enregistrement (logging) et de surveillance (monitoring) des historiques de couples de requêtes / réponses traités par les API, le tout couplé à une absence ou à une mauvaise gestion d'incidents, permet aux attaquants de poursuivre leurs attaques sur les systèmes, de s'y maintenir de manière persistante, voire de rebondir sur d'autres systèmes, d'extraire, de falsifier, ou encore de détruire des données. La plupart des études de failles montrent que le temps nécessaire pour détecter une intrusion est supérieur à 200 jours, typiquement découverte par des tiers externes plutôt que par des processus ou un monitoring interne. |
```

2021-07-10 11:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API10:2019 - Insufficient Logging & Monitoring | L'insuffisance de logging et de monitoring, couplée à une intégration insuffisante ou absente à la réponse aux incidents, permet aux attaquants de p
Première partie plus verbeuse, pas forcément utile ou pertinente.
Deuxième partie plus proche, selon moi, de la version orginale.

2021-07-11 16:39 UTC, llegaz requested changes
French translation -  review 2nd part
23 / 31 files viewed

2021-07-11 16:39 UTC, llegaz commented on 2019/fr/src/0xb1-next-devsecops.md
> +| **Stratégies de tests** | Comme votre travail ne doit pas impacter la vitesse de développement, vous devez choisir judicieusement la meilleure technique (simple, la plus rapide, la plus juste) pour
```suggestion
| **Stratégies de tests** | Comme votre travail ne doit pas impacter la vitesse de développement, vous devez choisir judicieusement la meilleure technique (simple, la plus rapide, la plus juste) pour vérifier les exigences de sécurité. Les projets [OWASP Security Knowledge Framework][4] et [OWASP Application Security Verification Standard][5] peuvent constituer d'excellentes sources d'exigences de sécurité fonctionnelles et non-fonctionnelles. Il existe également d'autres ressources et contenus de qualité tels les [projets][6] et [outils][7] proposés par la [communauté DevSecOps][8]. |
```

2021-07-11 16:39 UTC, llegaz commented on 2019/fr/src/0xb1-next-devsecops.md
> + Parmi les autres sources remarquent figurent les [projets][6] et [outils][7] proposés par la [communauté DevSecOps][8]. |
```suggestion

```

2021-07-11 16:39 UTC, llegaz commented on 2019/fr/src/0xb1-next-devsecops.md
> +| **Comprendre le SDLC** | Joignez-vous à l'équipe de développement pour mieux comprendre le cycle de développement logiciel (SDLC - Software Development Life Cycle). Votre contribution aux tests de
```suggestion
| **Comprendre le SDLC** | Joignez-vous à l'équipe de développement pour mieux comprendre le cycle de développement logiciel (SDLC - Software Development Life Cycle). Votre contribution aux tests de sécurité continus doit être compatible avec les personnes, les procédés et les outils. Tout le monde doit adhérer à la démarche, afin d'éviter des frictions ou de la résistance inutiles. |
```

2021-07-11 16:39 UTC, llegaz commented on 2019/fr/src/0xb1-next-devsecops.md
> +| **Comprendre le SDLC** | Joignez-vous à l'équipe de développement pour mieux comprendre le cycle de développement logiciel (SDLC - Software Development Life Cycle). Votre contribution aux tests de
Je pense qu'il faut garder le sens DevOps ici CI/CD, intégration continue et donc tests de sécu en continue à intégrer dans cette chaîne de production.

2021-07-11 16:39 UTC, llegaz commented on 2019/fr/src/0xb1-next-devsecops.md
> +| **Obtention de couverture et précision** | Vous êtes le lien entre les développeurs et les équipes des operations. Pour réaliser la couverture, vous devez vous concentrer non seulement sur la fonct
```suggestion
| **Obtention de couverture et précision** | Vous êtes le lien entre les développeurs (Dev) et les équipes opérationnelles (Ops). Pour réaliser la couverture, vous devez vous concentrer non seulement sur la fonctionnalité, mais aussi sur l'orchestration. Travaillez en étroite relation à la fois avec les équipes de développement et des opérations (infra) dès le début pour pouvoir optimiser votre temps et vos efforts. Vous devez viser un état où la sécurité essentielle est vérifiée continuellement. |
```

2021-07-11 16:39 UTC, llegaz commented on 2019/fr/src/0xb1-next-devsecops.md
> +| **Communication claire des résultats** | Apportez de la valeur avec pas ou peu de friction. Fournissez les résultats avec célérité, au sein des outils utilisés par les équipes de développement (pas
```suggestion
| **Communication claire des résultats** | Apportez de la valeur avec pas ou peu de friction. Alertez promptement sur vos découvertes, en utilisant les moyens et outils mis en oeuvres par vos équipes (pas dans des fichiers PDF). Joignez-vous à l'équipe de développement pour résoudre ces problèmes. Profitez de l'occasion pour les instruire, en décrivant clairement la vulnérabilité et la manière dont elle peut être exploitée, avec un scénario d'attaque pour la rendre réelle. |
```

2021-07-15 14:29 UTC, datakime commented on 2019/fr/src/0x11-t10.md
> +| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implémentés incorrectement, permettant à des attaquants de compromettre des tokens d'authentification ou d'ex
La notion de compromission dépasse l'utilisation à l'identique d'un jeton, elle inclut la possible manipulation d'un ou plusieurs de ses composants.

La notion d'implémentation renvoie à la conception/réalisation d'un projet (ici d'une API), celle d'implantation renvoyant à l'installation/configuration d'un logiciel.

Les termes compromission et implémentation ont été pareillement employés dans la version française de l'[OWASP Top 10 Risques Sécurités des Applications 2017](https://github.com/OWASP/Top10/blob/master/2017/fr/0x11-t10.md) (cf point A2).

2021-07-15 14:40 UTC, datakime commented on 2019/fr/src/0x11-t10.md
> +| API4:2019 - Lack of Resources & Rate Limiting | Bien souvent, les API n'imposent pas de restrictions sur la taille ou le nombre de ressources qui peuvent être requises par le client / l'utilisateur
L'original anglais fait référence à des ressources, pas des requêtes. Il ne mentionne pas non plus le type de ressources.

```APIs do not impose any restrictions on the size or number of resources that can be requested by the client/user.```

2021-07-15 14:52 UTC, datakime commented on 2019/fr/src/0x11-t10.md
> +| API6:2019 - Mass Assignment | La connexion de données fournies par le client (ex : JSON) aux modèles de données sans filtrage approprié par une liste de validation conduit généralement à l'assignat
L'original anglais emploie la même expression (object properties) à deux reprises dans la phrase. Utiliser alternativement attributs d'objets et propriétés d'objets pourrait d'entrainer des confusions.

Il est bien question de modifications (modify object properties), pas seulement d'accès à ces attributs.

2021-07-15 14:53 UTC, datakime commented on 2019/fr/src/0x11-t10.md
> +| API9:2019 - Improper Assets Management | Les API ont tendance à exposer plus de points d'accès que les applications web traditionnelles, rendant très importante la nécessité d'une documentation app
La portion de texte proposée en ajout ne figure pas dans l'original anglais.

2021-07-15 15:26 UTC, datakime commented on 2019/fr/src/0x11-t10.md
> +| API10:2019 - Insufficient Logging & Monitoring | L'insuffisance de logging et de monitoring, couplée à une intégration insuffisante ou absente à la réponse aux incidents, permet aux attaquants de p
Le passage proposé sur "des historiques de couples de requêtes / réponses traités par les API" n'est pas présent dans l'original anglais.
L'original mentionne explicitement l'absence ou l'insuffisance d'intégration à la réponse aux incidents. Remplacer intégration par gestion fait perdre en précision sur la nature du problème.

2021-07-15 15:42 UTC, datakime commented on 2019/fr/src/0xa1-broken-object-level-authorization.md
> +| Des attaquants peuvent exploiter des points d'accès d'API qui sont vulnérables à la faille de niveau d'autorisation en manipulant l'ID d'un objet qui est envoyé avec la requête. Ceci peut entrainer
On pourrait remplacer "typiquement" par "généralement". Mais en quoi la phrase n'est-elle pas juste par rapport à l'original anglais ?
 '''Access control detection is not typically amenable to automated static or dynamic testing.'''

2021-07-15 15:43 UTC, datakime commented on 2019/fr/src/0xa1-broken-object-level-authorization.md
> +* Implémentez un véritable mécanisme d'autorisation qui s'appuie sur des droits
idem précédent commentaire sur implémentation vs implantation

2021-07-15 15:46 UTC, datakime commented on 2019/fr/src/0xa2-broken-user-authentication.md
> +  et de protection par blocage.
L'original ne précise pas la nature du blocage opéré (compte, IP, etc)

2021-07-15 15:58 UTC, datakime commented on 2019/fr/src/0xa2-broken-user-authentication.md
> +  que le mécanisme de limitation de requêtes normal de votre API.
L'ajout proposé ne figure pas dans l'original anglais.

2021-07-15 15:58 UTC, datakime commented on 2019/fr/src/0xa2-broken-user-authentication.md
> +* Implémentez [le blocage de compte][4] / un mécanisme de captcha pour empêcher
idem précédents commentaires sur implémentation vs implantation

2021-07-15 15:58 UTC, datakime commented on 2019/fr/src/0xa2-broken-user-authentication.md
> +  l'emploi de force brute contre des utilisateurs spécifiques. Implementez des
idem précédents commentaires sur implémentation vs implantation

2021-07-15 16:01 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implémentés incorrectement, permettant à des attaquants de compromettre des tokens d'authentification ou d'ex
Personnellement je suis friand d'anglicismes donc cela ne me dérange pas plus. Mais tout de même, il semblerait qu'en français on parle bien d'implantation concernant la conception/réalisation de projet informatique (cf l'[académie](https://www.academie-francaise.fr/implementer)). J'ai même le souvenir d'utiliser le verbe "implémenter" à l'oral comme à l'écrit depuis très longtemps et d'avoir été sujet à de nombreuses remarques, notamment à l'école, mais passons.

2021-07-15 16:07 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API4:2019 - Lack of Resources & Rate Limiting | Bien souvent, les API n'imposent pas de restrictions sur la taille ou le nombre de ressources qui peuvent être requises par le client / l'utilisateur
L'original fait référence à des ressources qui sont requêtées et implicitiment réfère à la création des requêtes permettant d'obtenir ces ressources, tel que je le comprends : ce serait par example une API présentant des biens ou des personnes, disons des objets et laissant le soin au client de gérer la pagination et/ou le nombre d'objets demandés/retournés ensuite par l'API. S'il y a plusieurs millions de lignes en DB le DoS devient évident..

2021-07-15 16:11 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API4:2019 - Lack of Resources & Rate Limiting | Bien souvent, les API n'imposent pas de restrictions sur la taille ou le nombre de ressources qui peuvent être requises par le client / l'utilisateur
>  on the size or number of resources

Je pense qu'il faut voir ça comme la réponse structurée renvoyée par l'API.
Et donc, limitation de la taille de la réponse (=temps CPU en émission), du nombre d'objets (ou ressources) retourné (gestion de pagination server-side).

Mais vous avez raison, il faut reformuler encore.

2021-07-15 16:24 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API4:2019 - Lack of Resources & Rate Limiting | Bien souvent, les API n'imposent pas de restrictions sur la taille ou le nombre de ressources qui peuvent être requises par le client / l'utilisateur
Proposition
``
Bien souvent, les API n'imposent pas de restrictions sur le nombre de requêtes émises par un client d'API. Ou alors, n'imposent pas de restrictions sur le nombre ou la taille des ressources demandant à être accédées par le client / l'utilisateur et renvoyées en réponse.
``

2021-07-15 16:28 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API4:2019 - Lack of Resources & Rate Limiting | Bien souvent, les API n'imposent pas de restrictions sur la taille ou le nombre de ressources qui peuvent être requises par le client / l'utilisateur
Au passage, je pense que l'original devrait être étoffé car je suis sûr que le rate limiting est également mis en place pour limiter le nombre de requêtes reçues à la seconde pour un même client.
--
@PauloASilva 
By the way, I think the original should be expanded because I am sure that rate limiting is also in place to limit the number of requests received per second for the same client. As seen in real life projects.

2021-07-15 16:51 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API6:2019 - Mass Assignment | La connexion de données fournies par le client (ex : JSON) aux modèles de données sans filtrage approprié par une liste de validation conduit généralement à l'assignat
Je ne sais pas si le français est votre langue maternelle mais c'est mon cas : et personnellement l'utilisation de 3 fois d'affilé du terme "attribut" et 2 fois du verbe "modifier" dans la même fin de phrase me dérange profondément. La langue française est riche, utilisons des synonymes et encourageons les générations suivantes à ne pas standardiser notre langue en la rendant médiocre et sans saveur.

De plus, le sens n'est nullement altéré ici.

Et finalement, un coup il est question de `ressource` et un autre coup d'`objet` et bizarrement vous ne semblez pas perturbé plus que ça alors que l'on désigne pourtant la même chose sous 2 noms différents...

2021-07-15 16:55 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API6:2019 - Mass Assignment | La connexion de données fournies par le client (ex : JSON) aux modèles de données sans filtrage approprié par une liste de validation conduit généralement à l'assignat
Si accéder est trop soutenu pour vous et rend la compréhension de text difficile, alors on peut utiliser un synonyme plus évident comme `altérer` ou bien `remanier` ou encore très simplement `changer`.

2021-07-15 17:03 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API9:2019 - Improper Assets Management | Les API ont tendance à exposer plus de points d'accès que les applications web traditionnelles, rendant très importante la nécessité d'une documentation app
il me semble aussi que votre traduction n'est pas précise, il n'est pas question de `points de déboggage vulnérables` mais de  `exposed debug endpoints`.

Et où pensez-vous que ces endpoints ne devraient pas être accessibles ? En locale sur la machine d'un dev ? Sur un serveur de test ? En plus vous n'êtes pas cohérents car vous écrivez points d'accès tout du long pour le contracter en points ici.

Bref, reformulez comme vous le voulez mais  `points de déboggage vulnérables` n'est pas juste. Le problème avec un endpoint de Debug c'est qu'il arrive en production car ce n'est pas sa place (En prod, l'api est censée être livrée sans ou avec le moins de bugs possible et comme vous le savez la configuration sécurisée impose de donnez le moins d'informations possibles, messages d'erreurs, commentaires et outils de debug, qui sont eux liés au cycle de dev).

2021-07-15 17:17 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API10:2019 - Insufficient Logging & Monitoring | L'insuffisance de logging et de monitoring, couplée à une intégration insuffisante ou absente à la réponse aux incidents, permet aux attaquants de p
Et, bien plus que traduire bêtement, j'essaie de donner / garder le sens original.

Que pensez-vous qui doit être loggés et monitorés ? Les données comptables de l'entreprise ? 😂😂

Plus sérieusement, vous utilisez un moment le verbe `compromettre` (un mot que vous aimez particulièrement a priori) et pourtant il ne figure pas non plus dans **l'original anglais**. Alors quoi vous êtes le seul à avoir le droit d'interpréter le sens ?

> L'original mentionne explicitement l'absence ou l'insuffisance d'intégration à la réponse aux incidents.
Désolé, mais en France, dans les équipes Ops ou sécu on parle de gestion d'incident, c'est plus englobant, plus simple mais encore une fois le sens n'est pas altéré et selon moi cette tournure est plus pertinente, dans le sens que savoir si la gestion d'incidents et faites sur l'API ou si l'API est suffisament intégrée dans le process de gestion et de réponse aux incidents n'apporte strictement rien ici.

2021-07-15 17:20 UTC, llegaz commented on 2019/fr/src/0xa2-broken-user-authentication.md
> +  que le mécanisme de limitation de requêtes normal de votre API.
très bien

2021-07-15 17:22 UTC, llegaz commented on 2019/fr/src/0xa2-broken-user-authentication.md
> +  l'emploi de force brute contre des utilisateurs spécifiques. Implementez des
Oui idem, c'est toujours un anglicisme et son usage devrait être restraint, confère Académie Française au sujet du verbe **implémenter**.

2021-07-15 17:22 UTC, llegaz commented on 2019/fr/src/0xa2-broken-user-authentication.md
> +* Implémentez [le blocage de compte][4] / un mécanisme de captcha pour empêcher
Oui idem, c'est toujours un anglicisme et son usage devrait être restraint, confère Académie Française au sujet du verbe **implémenter**.

2021-07-15 17:38 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implémentés incorrectement, permettant à des attaquants de compromettre des tokens d'authentification ou d'ex
Comprenez bien, que même s'il est d'usage courant de parler d'implémentation en informatique. D'implémenter ça ou ça lorsque l'on s'adresse aux collègues ou bien aux clients, que cela nous semble à tous (IT guys) totalement nautrel, ça ne rend pas l'expression plus française et devrait donc être proscrite autant que faire se peut à l'écrit.

En ce qui concerne, "compromission", "compromettre un jeton d'auth." ce mot est parti intégrante du vocabulaire attribué à la sécurité informatique et à la sécurité en générale et donc son utilisation ici me dérange beaucoup moins. Je pensais que ma proposition, "d'obtenir" pour un attaquant d'une manière ou d'une autre, rendait le processus plus clair mais vous m'avez confirmé que non.

2021-07-16 08:46 UTC, PauloASilva commented on 2019/fr/src/0x11-t10.md
> +| API4:2019 - Lack of Resources & Rate Limiting | Bien souvent, les API n'imposent pas de restrictions sur la taille ou le nombre de ressources qui peuvent être requises par le client / l'utilisateur
@llegaz I see your point and completely agree: requests throttling is the most common use case for rate limiting, but I am afraid it would be tough to get all the translations updated accordingly.

Since [the corresponding section][1] covers request throttling, I suggest keeping this as is and open a new "enhancement" issue, so that we can take it into account for the next API Security Top 10 version (we should expect it to be released during 2022).

What do you think?

Cheers,
Paulo A. Silva

[1]: https://github.com/OWASP/API-Security/blob/master/2019/en/src/0xa4-lack-of-resources-and-rate-limiting.md#how-to-prevent

2021-08-03 18:00 UTC, llegaz commented on 2019/fr/src/0xaa-insufficient-logging-monitoring.md
> +  intégrité doit être garantie pour leur stockage comme pour leur transfert.
```suggestion
  intégrité doit être garantie durant leur stockage comme au cours de leur transfert.
```

2021-08-03 18:02 UTC, llegaz commented on 2019/fr/src/0xaa-insufficient-logging-monitoring.md
> +  agréger et gérer les logs de tous les composants de la pile et l'API et des
```suggestion
  agréger et gérer les logs de tous les composants de la pile de l'API et des
```

2021-08-03 18:03 UTC, llegaz commented on 2019/fr/src/0x11-t10.md
> +| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implémentés incorrectement, permettant à des attaquants de compromettre des tokens d'authentification ou d'ex
```suggestion
| API2:2019 - Broken User Authentication | Les mécanismes d'authentification sont souvent implémentés incorrectement, permettant à des attaquants de compromettre des jetons (Token) d'authentification ou d'exploiter des failles d'implémentation afin d'endosser temporairement ou de manière permanente l'identité d'autres utilisateurs. L'incapacité, pour un système, à identifier le client / utilisateur de manière fiable compromet la sécurité de l'API dans son ensemble. |
```

2021-08-03 18:07 UTC, llegaz commented on 2019/fr/src/0xa2-broken-user-authentication.md
> +* Implementez des mécanismes anti force brute pour empêcher le bourrage
```suggestion
* Implémentez des mécanismes anti force brute pour empêcher le bourrage
```

2021-08-03 18:28 UTC, llegaz commented on 2019/fr/src/0x10-api-security-risks.md
> +La [méthodologie d'évaluation de risques OWASP][1] a été utilisée pour effectuer l'analyse de risques.
```suggestion
La [méthodologie d'évaluation de risques OWASP][1] est utilisée pour effectuer l'analyse de risques.
```

2021-08-03 18:30 UTC, llegaz commented on 2019/fr/src/0xd0-about-data.md
> +et des discussions ouvertes avec la communauté de la sécurité.
```suggestion
et des discussions ouvertes avec la communauté de la sécurité informatique.
```

2021-12-23 17:06 UTC, datakime commented
Last but not least, distribution files added. 

@PauloASilva I used the Brazilian version as reference for page layout and page breaks. Had to reduce font size on page 'T10' to accomodate the full text, hope this is ok despite smaller size. If not, please let me know how to handle it

2021-12-28 11:50 UTC, merged